#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
# MICROHARD AGENCY — First-Time Setup
# Run once: bash scripts/setup.sh
# ═══════════════════════════════════════════════════════════════════

set -e

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo ""
echo "══════════════════════════════════════════════════"
echo "  MICROHARD AGENCY — Setup"
echo "══════════════════════════════════════════════════"
echo ""

# ── Check dependencies ─────────────────────────────────────────────
echo "→ Checking dependencies..."
command -v docker >/dev/null 2>&1 || { echo "✗ Docker not found. Install Docker first."; exit 1; }
command -v docker compose >/dev/null 2>&1 || { echo "✗ Docker Compose not found. Install Docker Compose V2."; exit 1; }
echo "  ✓ Docker found: $(docker --version)"
echo "  ✓ Docker Compose found: $(docker compose version)"

# ── Create .env ────────────────────────────────────────────────────
if [ -f ".env" ]; then
  echo ""
  echo "→ .env already exists — skipping generation"
else
  echo ""
  echo "→ Generating .env with secure secrets..."

  PLANE_SECRET=$(openssl rand -hex 32)
  PLANE_DB_PASS=$(openssl rand -hex 16)
  MINIO_USER=$(openssl rand -hex 12)
  MINIO_PASS=$(openssl rand -hex 24)
  IN_APP_KEY="base64:$(openssl rand -base64 32)"
  IN_DB_PASS=$(openssl rand -hex 16)
  IN_DB_ROOT=$(openssl rand -hex 16)

  cat > .env << EOF
# Generated by scripts/setup.sh on $(date)
# NEVER commit this file to git.

# ─── PLANE ────────────────────────────────────────────────────────
PLANE_SECRET_KEY=${PLANE_SECRET}
WEB_URL=http://localhost:33000
PLANE_DB_USER=plane
PLANE_DB_PASSWORD=${PLANE_DB_PASS}
PLANE_DB_NAME=plane
MINIO_ROOT_USER=${MINIO_USER}
MINIO_ROOT_PASSWORD=${MINIO_PASS}

# ─── INVOICE NINJA ───────────────────────────────────────────────
IN_APP_KEY=${IN_APP_KEY}
IN_DB_NAME=ninja
IN_DB_USER=ninja
IN_DB_PASSWORD=${IN_DB_PASS}
IN_DB_ROOT_PASSWORD=${IN_DB_ROOT}
EOF

  echo "  ✓ .env generated with fresh secrets"
fi

# ── Create data dirs ───────────────────────────────────────────────
echo ""
echo "→ Creating data directories..."
mkdir -p data/{plane-db,plane-redis,plane-minio,invoice-ninja/public,invoice-ninja/storage,invoice-ninja-db}
echo "  ✓ data/ directories created"

# ── Pull images ────────────────────────────────────────────────────
echo ""
echo "→ Pulling Docker images (this takes a few minutes on first run)..."
docker compose pull
echo "  ✓ Images pulled"

# ── Start stack ────────────────────────────────────────────────────
echo ""
echo "→ Starting services..."
docker compose up -d

echo ""
echo "→ Running Plane migrations (waiting for DB to be ready)..."
sleep 15
docker compose run --rm plane-migrator
echo "  ✓ Migrations complete"

# ── Create MinIO bucket ────────────────────────────────────────────
echo ""
echo "→ MinIO bucket setup running in background..."
docker compose up plane-minio-setup
echo "  ✓ MinIO uploads bucket ready"

# ── Done ──────────────────────────────────────────────────────────
echo ""
echo "══════════════════════════════════════════════════"
echo "  ✓ SETUP COMPLETE"
echo "══════════════════════════════════════════════════"
echo ""
echo "  Plane:          http://localhost:33000"
echo "  Invoice Ninja:  http://localhost:38080"
echo "  MinIO Console:  http://localhost:39090"
echo ""
echo "  Next steps:"
echo "  1. Open http://localhost:33000 → create your workspace"
echo "  2. Open http://localhost:38080 → configure Invoice Ninja"
echo "  3. Follow the setup checklist in output/plans/plane-architecture.md"
echo ""
